### ISSUE TITLE
Request to download the dataset

### ISSUE THREAD

**Issue by chaitanya100100** [m-bain/CondensedMovies-chall#3]
Hello,
I want to get access to this dataset. According to the instructions, I put up a request to maxbain@robots.ox.ac.uk email ID last week. However, I haven't received any update. Can you please look into it?
Thanks.

**Comment by anoubhav** [comment]
Were you able to access it?

**Comment by chaitanya100100** [comment]
Yes. Max replied back with dataset download links after a while.

**Comment by anoubhav** [comment]
Were the captions available, or they are supposed to be downloaded from YouTube? Also for each video was the actor level data present in the download links?

**Comment by chaitanya100100** [comment]
I have just downloaded the dataset. I haven't explored it yet.
